### ISSUE TITLE
Add label support

### ISSUE THREAD

**Issue by jaxxstorm** [jaxxstorm/puppet-teleport#3]
teleport supports labels when adding the SSH service:

``` yaml
# See explanation of labels in "Labeling Nodes" section below
    labels:
        role: master
        type: postgres
```

We should be able to use these labels by having a Puppet hash and then writing out the yaml from there.
