### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by jaxxstorm** [jaxxstorm/puppet-teleport#5]
Need to add SSL support to the yaml file for the proxy service:

``` yaml
# TLS certificate for the server-side HTTPS connection.
    # Configuring these properly is critical for Teleport security.
    https_key_file: /etc/teleport/teleport.key
    https_cert_file: /etc/teleport/teleport.crt
```
